language: python
python:
  - "2.7"
  - "3.4"
install: pip install -r requirements.txt
install: pip install -r requirements-dev.txt
script:
  py.test --cov-report term-missing --cov tai test
notifications:
  email:
    on_success: always
    on_failure: always
