language: python
python:
  - "2.7"
  - "3.4"
  - "pypy"
  #- "pypy3"
before_install: pip install pytest-cov
install:
  - "if [ $TRAVIS_PYTHON_VERSION != pypy ]; then pip install -r requirements.txt ; fi"
  - "if [ $TRAVIS_PYTHON_VERSION -eq pypy ]; then pip install pypy-dev ; fi"
  - "if [ $TRAVIS_PYTHON_VERSION -eq pypy ]; then pip install git+https://bitbucket.org/pypy/numpy.git ; fi"
script: py.test --cov-report term-missing --cov tai -v test
notifications:
  email:
    on_success: always
    on_failure: always
