environment:

  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    WITH_COMPILER: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_compiler.cmd"

  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.9"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.4.3"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.9"
      PYTHON_ARCH: "64"
      WINDOWS_SDK_VERSION: "v7.0"

    # commented until numpy build problem is solved
    #- PYTHON: "C:\\Python34-x64"
    #  PYTHON_VERSION: "3.4.3"
    #  PYTHON_ARCH: "64"
    #  WINDOWS_SDK_VERSION: "v7.1"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "powershell appveyor\\install.ps1"
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "pip install twine pytest pytest-cov Sphinx"
  - "pip install -r requirements.txt"

# It's off because it doesn't apply to Python
build: off

test_script:
  #- "%WITH_COMPILER% %PYTHON%/python setup.py test"
  #- "%WITH_COMPILER% %PYTHON%/python py.test --cov tai -v test"
  - "%WITH_COMPILER% py.test --cov-report term-missing --cov tai -v test"

after_test:
  - "%WITH_COMPILER% %PYTHON%/python setup.py sdist bdist_wheel"
  #- "pip install dist/*"
  # check  Python version
  - "%WITH_COMPILER% %PYTHON%/python -V"

artifacts:
  - path: dist\*

#on_success:
#  - "%WITH_COMPILER% %PYTHON%/python setup.py register -r pypi"
#  - "twine upload dist/*"
#  - "if exist tai\\doc %WITH_COMPILER% %PYTHON%/python setup.py register upload_docs --upload-dir=tai\\doc"

notifications:
  - provider: Email
    to:
      - jcrmatos@gmail.com
    on_build_success: true
    on_build_failure: true
    #on_build_status_changed: true
